### ISSUE TITLE
graphql.language.IntValue cannot be cast to graphql.language.FloatValue

### ISSUE THREAD

**Issue by hannesj** [andimarek/graphql-java#13]
Hi,

If I have an argument which has the type of Scalars.GraphQLFloat, I get the above mentioned error, if the float value can be interpreted as an integer (eg. 10.0).

**Comment by andimarek** [comment]
Could you provide more details? E.g. the exception stracktrace

The literal 10.0 is parsed as a float value, so I'm little bit unsure where this problem comes from.

Thanks

**Comment by andimarek** [comment]
Hi @hannesj,

could you provide more details about this?

Thanks

**Comment by hannesj** [comment]
Hi,

The problem seems to come from the fact that JavaScript does only have the Number type, so that values like `10.0` get outputted as `10` in queries created in JavaScript.

However, the [specification](https://facebook.github.io/graphql/#sec-Float) states that `When expected as an input type, both integer and float input values are accepted. Integer input values are coerced to Float by adding an empty fractional part, for example 1.0 for the integer input value 1. `, which the code doesn't currently adhere to. The easiest fix is probably modifying [this](https://github.com/andimarek/graphql-java/blob/master/src/main/java/graphql/Scalars.java#L69) to check If the type is and casting its value to float.

**Comment by pasviegas** [comment]
The javascript version also converts null numbers to 0.

The specification does not say it clearly, but "when possible" would also hold for null as primitive/js int null is 0.

`GraphQL servers should coerce non‐int raw values to Int when possible otherwise they must raise a field error. Examples of this may include returning 1 for the floating‐point number 1.0, or 2 for the string "2".`

This also affects floats as ints should be converted to floats.

**Comment by andimarek** [comment]
@hannesj The problem should be fixed:  https://github.com/andimarek/graphql-java/commit/34145726d7a335ca3d70a84bad9abcdfe6e45af8 

Float accepts now also int as input

**Comment by hannesj** [comment]
Thanks @andimarek!
