### ISSUE TITLE
Class cast exception in introspection query

### ISSUE THREAD

**Issue by Hellblazer** [andimarek/graphql-java#31]
I have a simple test that creates a schema that has a non null string argument.  When I perform an introspection query that includes the default value, it fails.  I have learned my lesson and created a gist of the test for this issue:  https://gist.github.com/Hellblazer/ced9f0dd53e798452f29

I thought I'd check with you to ensure that this was actually a bug and not operator error before I delved into fixing this.

**Comment by andimarek** [comment]
With the latest version I don't get a ClassCasteException. But I get an validation error because the field "defaultValue" is not known. You can't query a defaultValue on a type, but on the args, so you can do this:

query IntrospectionQueryTypeQuery { __schema { queryType { fields { name args { name description defaultValue type { name kind ofType { name kind } } } } } } }

**Comment by Hellblazer** [comment]
Ugh.  I misplaced that.  Should be as you corrected.   So I looked at Introspection on master and indeed, line 87 (85 in 1.2) is where you are handling what I'm seeing a GraphQLArgument attempting to be cast as a GraphQLInputObjectField.

Excellent.  Again, thanks!
